// resources/js/components/ui/label/Label.vue
<script setup lang="ts">

import type { LabelProps, } from "reka-ui";
import type { HTMLAttributes, } from "vue";
import { reactiveOmit, } from "@vueuse/core";
import { Label, } from "reka-ui";
import { cn, } from "@/lib/utils";

const props = defineProps<LabelProps & { class?: HTMLAttributes["class"]; }> ();

const delegatedProps = reactiveOmit (props, "class");

</script>

<template>
    <Label
        v-bind="delegatedProps"
        :class="
            cn (
                'text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
                props.class,
            )
        "
    >
        <slot />
    </Label>
</template>

// resources/js/components/ui/label.tsx
import * as LabelPrimitive from "@radix-ui/react-label";
import * as React from "react";

import { cn, } from "@/lib/utils";

const Label = ({
    className,
    ... props
}: React.ComponentProps<typeof LabelPrimitive.Root>): React.ReactElement =>
{
    return (
        <LabelPrimitive.Root
            data-slot="label"
            className={cn (
                "text-sm leading-none font-medium select-none group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50",
                className
            )}
            {... props}
        />
    );
};

export { Label, };
