// resources/js/components/ui/spinner/Spinner.vue
<script setup lang="ts">

import type { HTMLAttributes, } from "vue";
import { Loader2, } from "lucide-vue-next";
import { cn, } from "@/lib/utils";

interface Props
{
    class?: HTMLAttributes["class"];
};

const props = defineProps<Props> ();

</script>

<template>
    <Loader2
        role="status"
        :class="cn ('size-4 animate-spin', props.class)"
        v-bind="$attrs"
    />
</template>

// resources/js/components/ui/spinner.tsx
import { ReactElement, } from "react";
import { Loader2Icon, } from "lucide-react";

import { cn, } from "@/lib/utils";

const Spinner = ({ className, ... props }: React.ComponentProps<"svg">): React.ReactElement =>
{
    return (
        <Loader2Icon
            role="status"
            className={cn ("size-4 animate-spin", className)}
            {... props}
        />
    );
};

export { Spinner, };
