// resources/js/components/ui/input.tsx
import * as React from "react";

import { cn, } from "@/lib/utils";

const Input = ({ className, type, ... props }: React.ComponentProps<"input">): React.ReactElement =>
{
    return (
        <input
            type={type}
            className={cn (
                "flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium file:text-foreground placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50",
                className
            )}
            {... props}
        />
    );
};

export { Input, };

// resources/js/components/ui/input/Input.vue
<script setup lang="ts">

import type { HTMLAttributes, } from "vue";
import { useVModel, } from "@vueuse/core";
import { cn, } from "@/lib/utils";

const props = defineProps<{
    defaultValue?: string | number;
    modelValue?: string | number;
    class?: HTMLAttributes["class"];
}> ();

const emits = defineEmits<{
    (e: "update:modelValue", payload: string | number): void;
}> ();

const modelValue = useVModel (props, "modelValue", emits, {
    passive: true,
    defaultValue: props.defaultValue,
});

</script>

<template>
    <input
        v-model="modelValue"
        v-bind="$attrs"
        :class="cn ('flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50', props.class)"
    />
</template>
