// resources/js/components/ui/checkbox.tsx
import * as CheckboxPrimitive from "@radix-ui/react-checkbox";
import { CheckIcon, } from "lucide-react";
import * as React from "react";

import { cn, } from "@/lib/utils";

const Checkbox = ({
    className,
    ... props
}: React.ComponentProps<typeof CheckboxPrimitive.Root>): React.ReactElement =>
{
    return (
        <CheckboxPrimitive.Root
            data-slot="checkbox"
            className={cn (
                "peer border-input data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground data-[state=checked]:border-primary focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive size-4 shrink-0 rounded-[4px] border shadow-xs transition-shadow outline-none focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50",
                className
            )}
            {... props}
        >
            <CheckboxPrimitive.Indicator
                data-slot="checkbox-indicator"
                className="flex items-center justify-center text-current transition-none"
            >
                <CheckIcon className="size-3.5" />
            </CheckboxPrimitive.Indicator>
        </CheckboxPrimitive.Root>
    );
};

export { Checkbox, };

// resources/js/components/ui/checkbox/Checkbox.vue
<script setup lang="ts">

import type { CheckboxRootEmits, CheckboxRootProps, } from "reka-ui";
import type { HTMLAttributes, } from "vue";
import { reactiveOmit, } from "@vueuse/core";
import { Check, } from "lucide-vue-next";
import { CheckboxIndicator, CheckboxRoot, useForwardPropsEmits, } from "reka-ui";
import { cn, } from "@/lib/utils";

const props = defineProps<CheckboxRootProps & { class?: HTMLAttributes["class"]; }> ();
const emits = defineEmits<CheckboxRootEmits> ();

const delegatedProps = reactiveOmit (props, "class");

const forwarded = useForwardPropsEmits (delegatedProps, emits);

</script>

<template>
    <CheckboxRoot
        v-bind="forwarded"
        :class="
            cn (
                'grid place-content-center peer h-4 w-4 shrink-0 rounded-sm border border-primary shadow focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground',
                props.class
            )
        "
    >
        <CheckboxIndicator class="grid place-content-center text-current">
            <slot>
                <Check class="h-4 w-4" />
            </slot>
        </CheckboxIndicator>
    </CheckboxRoot>
</template>
