// resources/js/components/input-error.tsx
import { FC, type HTMLAttributes, } from "react";

import { cn, } from "@/lib/utils";

interface InputErrorProps extends HTMLAttributes<HTMLParagraphElement>
{
    message?: string;
};

const InputError: FC<InputErrorProps> = ({
    message,
    className = "",
    ...props
}) =>
{
    return message ? (
        <p
            {...props}
            className={cn ("text-sm text-red-600 dark:text-red-400", className)}
        >
            {message}
        </p>
    ) : null;
};

export default InputError;

// resources/js/components/input-error/InputError.vue
<script setup lang="ts">

import type { HTMLAttributes, } from "vue";
import { cn, } from "@/lib/utils";

interface Props
{
    message?: string;
    class?: HTMLAttributes["class"];
};

const props = defineProps<Props> ();

</script>

<template>
    <p
        v-if="props.message"
        :class="cn ('text-sm text-red-600 dark:text-red-400', props.class)"
        v-bind="$attrs"
    >
        {{ props.message }}
    </p>
</template>
