// resources/js/components/alert-error/AlertError.vue
<script setup lang="ts">

import { AlertCircle, } from "lucide-vue-next";
import { Alert, AlertDescription, AlertTitle, } from "@/components/ui/alert";
import { useI18n, } from "@/composables/useI18n";

interface Props
{
    errors: string[];
    title?: string;
};

const props = defineProps<Props> ();

const { t, } = useI18n ();

</script>

<template>
    <Alert variant="destructive">
        <AlertCircle />
        <AlertTitle>{{ props.title || t ("common.something_went_wrong") }}</AlertTitle>
        <AlertDescription>
            <ul class="list-inside list-disc text-sm">
                <li
                    v-for="(error, index) in Array.from (new Set (props.errors))"
                    :key="index"
                >
                    {{ error }}
                </li>
            </ul>
        </AlertDescription>
    </Alert>
</template>

// resources/js/components/alert-error.tsx
import { FC, } from "react";
import { useTranslation, } from "react-i18next";
import { AlertCircleIcon, } from "lucide-react";

import { Alert, AlertDescription, AlertTitle, } from "@/components/ui/alert";

interface AlertErrorProps
{
    errors: string[];
    title?: string;
};

const AlertError: FC<AlertErrorProps> = ({
    errors,
    title,
}) =>
{
    const { t, }: { t: Function; } = useTranslation ();

    return (
        <Alert variant="destructive">
            <AlertCircleIcon />
            <AlertTitle>{title || t ("common.something_went_wrong")}</AlertTitle>
            <AlertDescription>
                <ul className="list-inside list-disc text-sm">
                    {Array.from (new Set (errors)).map ((error, index) => (
                        <li key={index}>{error}</li>
                    ))}
                </ul>
            </AlertDescription>
        </Alert>
    );
};

export default AlertError;
